### ISSUE TITLE
Launching Tin Can activity in Moodle Error: Exception - DateInterval::__construct(): Unknown or bad format (PTM)

### ISSUE THREAD

**Issue by dansclan** [davidpesce/moodle-mod_tincanlaunch#111]
The Tincanlaunch is communicating from Moodle to Learning Locker.  I get a statement in Learning that the activity is launched but in Moodle I get this error: Exception - DateInterval::__construct(): Unknown or bad format (PTM)

Need some help in resolving this.

Thank you

**Comment by garemoko** [comment]
Thanks for reporting this @dansclan. I'll need a LOT more details in order to debug this though. 

For example: 
- Where are you seeing that error? 
- What statements are landing in Learning Locker? (please include the full JSON)
- What happens when you try with SCORM Cloud? 
- What versions of Moodle and Learning Locker are you using? 
- What (in great detail) are you doing when this error occurs? 
- Where did you get the plugin from and what version are you using
- Anything else you can think of; there's no such thing as too much information.

**Comment by dansclan** [comment]
I have resolved this issue.  I decided to try uninstalling and reinstalling.  Through that process, found out that there were some missing files in the Moodle installation.  It was converted from an internal windows server to a hosted linux server and apparently it did not all convert.  So, once those were installed, I was able to install the plugin and it is now working.

thank you
