### ISSUE TITLE
module instance within a course not included in course backups

### ISSUE THREAD

**Issue by logan-reynolds** [davidpesce/moodle-mod_tincanlaunch#118]
Testing both version 2015033100 release 1.1 on Moodle 2.9 and latest version 2016060300 release 1.3RC2 on Moodle 3.1, I'm seeing that when attempting to backup a course containing an xAPI activity module instance it is **not** available to be included on the course backup page, and therefore is not present in subsequent restored courses.  Typically, any activity instances present in a given course are expected to persist across course backup/restore, and the plugin code likely just needs updated for newer M29+ course backup requirements.

**Comment by garemoko** [comment]
Thanks for flagging this. Course backup and restore functionality is not something I've tested or worked on so I'm not surprised by this. 

I've tagged this as low priority because I don't believe that course back up and restore is a well used feature (it's not come up previously) and this is not something I'm planning to address myself. 

Pull requests are very welcome if somebody else wants to take this on.

**Comment by ghost** [comment]
Thank you; I've submitted a pull request at https://github.com/garemoko/moodle-mod_tincanlaunch/pull/122 that appears to fix backup/restore on M2.0 and higher.  I also wanted to ask whether newly-released versions could also be published to the plugin page on Moodle.org at https://moodle.org/plugins/mod_tincanlaunch , since AFAIK we need to retrieve the version deployed from that location to get the included TinCanPHP libraries.  Please let me know if there's anything further I can provide, and thank you for your work on this plugin.

Regards,
Logan Reynolds

**Comment by garemoko** [comment]
This PR is now merged and I'll be doing a release soon. Thanks!
