### ISSUE TITLE
Install In Moodle 3.3 Error

### ISSUE THREAD

**Issue by ffnando** [davidpesce/moodle-mod_tincanlaunch#137]
How To install in my Moodle 3.3 ?
please update plugin version

**Comment by garemoko** [comment]
Hi, 
Thanks for logging an issue. It's not clear what your problem is though. Please can you provide a lot more detail and screenshots of what you're doing and any errors?

I should also let you know that I'm unlikely to have any time to fix issues and even test submitted PRs any time soon. However if somebody makes a fix and somebody else tests it and confirms it all works, I'll make the time to do the merge (and release if appropriate).

**Comment by ffnando** [comment]
![why](https://user-images.githubusercontent.com/8979421/27062013-5762fb5e-5012-11e7-939b-84cb1370af32.PNG)
please helpme

**Comment by garemoko** [comment]
Ok. You need to install the plugin from the Moodle plugins directory, not directly from github. 

Please follow the instructions outlined in the readme: https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/README.md
