### ISSUE TITLE
Content closed Notification 

### ISSUE THREAD

**Issue by Getafix-hub** [davidpesce/moodle-mod_tincanlaunch#171]
Does the plugin allow/could be extended to register a callback:
- when the content window has been closed? 
- when the activity has been completed?

**Comment by garemoko** [comment]
@chrgrd I don't think the first one is possible since the plugin does not open a pop-up but an independent window (because nobody likes blocked pop-ups). 

There is functionality for the plugin to fetch completion data from the LRS, but that functionality is bad. There are already issues around that.
