### ISSUE TITLE
Question - appropriate place to put extra field in xAPI

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#40]
This may be the wrong place for this, but you're my go to xAPI expert. Feel free to delete if it's misplaced.

I have a unique identifier within Moodle (set as a custom field) and would like it to be stored with the the statements. Where would this be appropriate to place within a statement?

**Comment by scara** [comment]
If it is related to the scope of your experience it could be added in the `id` otherwise IMHO [Extensions](https://github.com/adlnet/xAPI-Spec/blob/a752217060b83a2e15dfab69f8c257cd86a888e6/xAPI.md#53-extensions) is the right place: the [_Details_](https://github.com/adlnet/xAPI-Spec/blob/a752217060b83a2e15dfab69f8c257cd86a888e6/xAPI.md#details-24) section will give you some hints.

**Comment by garemoko** [comment]
It really depends on what the unique identifier is uniquely identifying!

**Comment by davidpesce** [comment]
Sorry, that info would've helped! It's a UUID (for users).

**Comment by garemoko** [comment]
Is it the main identifier for your users? If not, what is it?

**Comment by davidpesce** [comment]
It's not the main identifier from the Moodle standpoint, but is from an external system. Would like to match them up so that reports have this information within them.

**Comment by garemoko** [comment]
This is actually one area of Tin Can that's a little more complicated than you might think. Tin Can references [personas rather than people](http://tincanapi.com/2013/06/05/deep-dive-actor-agent/?utm_source=tincanapi_com&utm_medium=github&utm_term=andrew&utm_content=blog&utm_campaign=deep-dive-agent?pmc=em-1) which means that if you have two separate identifiers for a person, this is two separate personas. This is designed to avoid systems accidentally associating two personas of a person that they wanted to keep separate. It's a privacy thing. 

The implication for you is that you shouldn't include more than one identifier for a person (or more than one persona identifier, to put it another way) in each statement. Instead, you should have a way for tools consuming the data to associate the two identifiers. You've got a few options:
1. Store the data in the external system.
2. Store the data in Moodle.
3. Store the data in the LRS.
4. Some combination of the above. 

Considering which tools in your ecosystem need to know the identifiers match a single person, which do you think would be most appropriate for you?

**Comment by davidpesce** [comment]
This is resolved.
