### ISSUE TITLE
Warning message

### ISSUE THREAD

**Issue by ReneBreedveld** [davidpesce/moodle-mod_tincanlaunch#63]
When executing a Tin Can course I receive the following warning message: 'There was a problem communicating with the Learning Record Store (400 | Activity ID 'null' is not an absolute URI). Triangle exists of Moodle 2.8.5 - Scorm Cloud (already contacted Rustici Software support ticket: 22126) and Lectora Publisher 11.3 (9201). Result: course will not start.

**Comment by garemoko** [comment]
Hi Rene, 

Joe Donnelly on the support desk actually looped me in to your ticket and I took a look. You've probably already had this information from Joe, but here it is anyway:

It looks like you are not doing anything wrong, but there's an incompatibility between this course and the Moodle launch plugin and some code changes in one or the other would be required for them to work together. Your choices are to contact Lectora and see if they will make a change, or to modify the Moodle plugin. 

The code changes on the Moodle plugin would be relatively minimal. You could get the latest version of the code and add a new line in at https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/locallib.php#L222 

`"activity_id" => $tincanlaunchsettings['tincanactivityid']`

You will also need to add a comma at the end of the preceding line. Just to be extra helpful, I've made this change for you in a branch which you can download here: https://github.com/garemoko/moodle-mod_tincanlaunch/archive/lectora.zip

As the Moodle plugin maintainer, I wouldn't make this change myself or even accept it as a Pull Request (without some settings to configure this and have it turned off by default). There's no reason why you can't make the change in your own copy of the plugin though. The reasons I don't want this code in the plugin are:
- cmi5 uses 'activityId' instead of 'activity_id' so I wouldn't want to include this code unless there was an additional setting to allow the Moodle course admin to choose which format to use. 
- the e-learning course shouldn't require an activity id to be passed in order to function. The launch spec says "Partial launch information may also be provided by an LMS in the form of a launch link, which may consist of only endpoint information, or may include learner information but not credentials. In this case, the AP would have to have been configured with or prompt for the necessary information."
- It's my opinion that it's bad practice for the LMS to specify the activity id, or at least for the content to use an activity id passed from the LMS. The activity id should be the same wherever the content is launched from. I wouldn't want to include this code unless passing the activity id is configured off by default but can be turned on as an advanced setting. 
  - Note: SCORM Cloud does pass the activity id, but it uses the id specified within the content's own tincan.xml so it's only reflecting the content's own activity id back at it, which is fine. The Moodle plugin does not current support importing packages or reading tincan.xml files so it can't do that. 

An alternative solution if Rene is using SCORM Cloud is to use the SCORM Cloud integration Moodle plugin. I believe this will use up registrations though, whereas he can use the launch plugin with the free LRS.

**Comment by ReneBreedveld** [comment]
Hi Andrew,

Thank you for your reply and you’re right about the fact that Joe gave me already the information and I did change the line 222 in my own plugin without success. But, in the meantime I’ve contacted the Courseware Company support (ticket: 15547) and asked them to help me with Lectora. 

So, the issue is pending.

With kind regards, 

René 

Van: Andrew Downes [mailto:notifications@github.com] 
Verzonden: donderdag 7 mei 2015 12:30
Aan: garemoko/moodle-mod_tincanlaunch
CC: ReneBreedveld
Onderwerp: Re: [moodle-mod_tincanlaunch] Warning message (#63)

Hi Rene, 

Joe Donnelly on the support desk actually looped me in to your ticket and I took a look. You've probably already had this information from Joe, but here it is anyway:

It looks like you are not doing anything wrong, but there's an incompatibility between this course and the Moodle launch plugin and some code changes in one or the other would be required for them to work together. Your choices are to contact Lectora and see if they will make a change, or to modify the Moodle plugin. 

The code changes on the Moodle plugin would be relatively minimal. You could get the latest version of the code and add a new line in at https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/locallib.php#L222 

"activity_id" => $tincanlaunchsettings['tincanactivityid']

You will also need to add a comma at the end of the preceding line. Just to be extra helpful, I've made this change for you in a branch which you can download here: https://github.com/garemoko/moodle-mod_tincanlaunch/archive/lectora.zip

As the Moodle plugin maintainer, I wouldn't make this change myself or even accept it as a Pull Request (without some settings to configure this and have it turned off by default). There's no reason why you can't make the change in your own copy of the plugin though. The reasons I don't want this code in the plugin are:

·         cmi5 uses 'activityId' instead of 'activity_id' so I wouldn't want to include this code unless there was an additional setting to allow the Moodle course admin to choose which format to use. 

·         the e-learning course shouldn't require an activity id to be passed in order to function. The launch spec says "Partial launch information may also be provided by an LMS in the form of a launch link, which may consist of only endpoint information, or may include learner information but not credentials. In this case, the AP would have to have been configured with or prompt for the necessary information."

·         It's my opinion that it's bad practice for the LMS to specify the activity id, or at least for the content to use an activity id passed from the LMS. The activity id should be the same wherever the content is launched from. I wouldn't want to include this code unless passing the activity id is configured off by default but can be turned on as an advanced setting. 
-   Note: SCORM Cloud does pass the activity id, but it uses the id specified within the content's own tincan.xml so it's only reflecting the content's own activity id back at it, which is fine. The Moodle plugin does not current support importing packages or reading tincan.xml files so it can't do that. 

An alternative solution if Rene is using SCORM Cloud is to use the SCORM Cloud integration Moodle plugin. I believe this will use up registrations though, whereas he can use the launch plugin with the free LRS.

**Comment by garemoko** [comment]
Hi,

It looks like I made an error in the line of code to change. The correct code was 
`"activity_id" => $tincanlaunch->tincanactivityid`

Try this version of the plugin: https://github.com/garemoko/moodle-mod_tincanlaunch/archive/lectora.zip

**Comment by ReneBreedveld** [comment]
Hello Andrew,

Thank you for the new version of the plugin. I’ve uploaded it to Moodle and started the TinCan. Now I see the following changed message:

So, something is happening, but not solved yet, 

René

Van: Andrew Downes [mailto:notifications@github.com] 
Verzonden: donderdag 7 mei 2015 14:50
Aan: garemoko/moodle-mod_tincanlaunch
CC: ReneBreedveld
Onderwerp: Re: [moodle-mod_tincanlaunch] Warning message (#63)

Hi,

It looks like I made an error in the line of code to change. The correct code was 
"activity_id" => $tincanlaunch->tincanactivityid

Try this version of the plugin: https://github.com/garemoko/moodle-mod_tincanlaunch/archive/lectora.zip

**Comment by garemoko** [comment]
Hi Rene, 
I'm guessing you added an image but it's not come through. Can you come to https://github.com/garemoko/moodle-mod_tincanlaunch/issues/63 to upload the image or email it to andrew.downes@tincanapi.com ?

**Comment by ReneBreedveld** [comment]
Hello Andrew,

Thank you for your reply.

It’s more than an one image. It’s a flash file and causing problems. So, , I did change the TinCan a bit and you w’ll find the result in our shared  Dropbox folder ReneShare.

With kind regards,

René

Van: Andrew Downes [mailto:notifications@github.com] 
Verzonden: donderdag 7 mei 2015 16:54
Aan: garemoko/moodle-mod_tincanlaunch
CC: ReneBreedveld
Onderwerp: Re: [moodle-mod_tincanlaunch] Warning message (#63)

Hi Rene, 
I'm guessing you added an image but it's not come through. Can you come to #63 https://github.com/garemoko/moodle-mod_tincanlaunch/issues/63  to upload the image or email it to andrew.downes@tincanapi.com ?

**Comment by garemoko** [comment]
Could you take a screenshot of the error or tell me the text of what it says?

**Comment by ReneBreedveld** [comment]
Van: Andrew Downes [mailto:notifications@github.com] 
Verzonden: vrijdag 8 mei 2015 11:14
Aan: garemoko/moodle-mod_tincanlaunch
CC: ReneBreedveld
Onderwerp: Re: [moodle-mod_tincanlaunch] Warning message (#63)

Could you take a screenshot of the error or tell me the text of what it says?

**Comment by garemoko** [comment]
Can you upload the screenshot at https://github.com/garemoko/moodle-mod_tincanlaunch/issues/63 or email it to andrew.downes@tincanapi.com?
