### ISSUE TITLE
moodleform_mod::add_intro_editor() is deprecated

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#64]
Adding this here so I don't forget:

```
Function moodleform_mod::add_intro_editor() is deprecated, use moodleform_mod::standard_intro_elements() instead.

    line 700 of /course/moodleform_mod.php: call to debugging()
    line 64 of /mod/tincanlaunch/mod_form.php: call to moodleform_mod->add_intro_editor()
    line 191 of /lib/formslib.php: call to mod_tincanlaunch_mod_form->definition()
    line 86 of /course/moodleform_mod.php: call to moodleform->moodleform()
    line 255 of /course/modedit.php: call to moodleform_mod->moodleform_mod()
```

Moodle 2.9+ (Build: 20150612)

**Comment by garemoko** [comment]
Thanks @davidpesce

**Comment by scara** [comment]
FYI, https://tracker.moodle.org/browse/MDL-50321 for the missing mention - as per the normal Moodle deprecation guidelines - and https://tracker.moodle.org/browse/MDL-49101 where the actual deprecation took place.
Based on the minimum supported Moodle version by the plug-in, it could be required to select the method based on the Moodle version (see https://docs.moodle.org/dev/Releases) in order to keep the same branch for different Moodle API versions.

HTH,
Matteo

**Comment by garemoko** [comment]
Fixed in next commit
