### ISSUE TITLE
Plugin files and folder structure

### ISSUE THREAD

**Issue by nadavkav** [davidpesce/moodle-mod_tincanlaunch#7]
Hi Andrew,

It seems that all Moodle plugins follow some kind of a folder and files structure guideline (I think) in which the plugin's files and subfolders are available on the main repository tree and not in a subfolder, as you are using.

Your folder structure is causing some GIT management issues when I clone it into my Moodle tree.

I am unable to use:
"git clone https://github.com/garemoko/moodle-mod_tincanlaunch.git mod/tincanlaunch"
As it creates mod/tincanlaunch/tincanlaunch in my Moodle folder.

Please see if you can fix the way you structure files and folder inside your repository. If it is not too much trouble :smiley: 

Kindly,
Nadav :smiley:

**Comment by garemoko** [comment]
Hi Nadav,
I'm not keen to change this because it will mean I have to rename the folder every time I copy it into my Moodle folder in Windows. 

Could you do "git clone https://github.com/garemoko/moodle-mod_tincanlaunch.git mod"

You'd then need to delete the github read me.md

Or just download the zip and drop it in?

Andrew

**Comment by nadavkav** [comment]
You are right. silly me.

Thanks :smiley:
