### ISSUE TITLE
There was a problem communicating with the Learning Record Store. 401

### ISSUE THREAD

**Issue by openflips** [davidpesce/moodle-mod_tincanlaunch#8]
Hi Andrew,

I've managed to setup a launch link for the Golf prototype from tincanapi.com .

I'm getting an error message : 

[warning] There was a problem communicating with the Learning Record Store. (401 | <html>
 <head>
  <title>401 Unauthorized</title>
 </head>
 <body>
  <h1>401 Unauthorized</h1>
  This server could not verify that you are authorized to access the document you requested.  Either you supplied the wrong credentials (e.g., bad password), or your browser does not understand how to supply the credentials required.<br/><br/>
You are not authorized for this instance.
 </body>
</html>)

In Wax LRS, I've created "Basic Credentials" and copy pasted the login and password to the launch link settings.

Am I missing something ?

Many thanks

**Comment by garemoko** [comment]
Hi,
Please send me three screenshots:
1. Your Wax LRS settings page.
2. The plugin settings.
3. The error message. 

If you don't want to publicise these, can you mail me at mrdownes@hotmail.com ?

**Comment by garemoko** [comment]
Hi, 
No need for screenshots. I was able to replicate. The problem was that PHP was following RFC 1738 and encoding the spaces in the URL as '+' whereas the JavaScript was expecting RFC 3986 encoding (%20). I've updated the plugin to replace + with %20 in the encoded query string. 

This works with my particular LRS credentials, but it's possible that there could be a legitimate + sign in the base 64 encoding so I'm going to need to have more of a think. 

It would be easy to fix if I could assume PHP version 5.4 as this supports RFC 3986 encoding, but Moodle 2.5 is supposed to support PHP 5.3.3.

Andrew

**Comment by garemoko** [comment]
That should do it.

 https://github.com/garemoko/moodle-mod_tincanlaunch/commit/0feb0af2b9f141168ca404bd51f4d5fcf9e5e72b

Fortunately the rawurlencode function conforms to RFC 3986 encoding from PHP version 5.3.0, so we're good. It's just http_build_query that is the issue. 

Get the latest version of the code here: https://github.com/garemoko/moodle-mod_tincanlaunch/archive/0feb0af2b9f141168ca404bd51f4d5fcf9e5e72b.zip and it should work.
