### ISSUE TITLE
Unable to launch the course

### ISSUE THREAD

**Issue by olivierplante** [davidpesce/moodle-mod_tincanlaunch#95]
Hi,

I have some problems launching my course. I can create new registration but when I launch them I got this error :

Fatal error: Class 'TinCan\statement' not found in /opt/bitnami/apps/moodle/htdocs/mod/tincanlaunch/locallib.php on line 69

What can I do to fix it?

**Comment by garemoko** [comment]
Hi,
This is fixed in the master branch here: https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/locallib.php#L69

Are you using the latest version of the plugin from the plugins directory? Possibly I need to do another release. 

This seems to only affect some people - what server are you running?

Thanks!

**Comment by olivierplante** [comment]
I use the latest version i found here https://moodle.org/plugins/mod_tincanlaunch.

**Comment by garemoko** [comment]
Ok. I'll need to do an update. Thank you. 

For now you can update your code by copying the line here into your copy of the plugin: https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/locallib.php#L69

**Comment by olivierplante** [comment]
Thank you for your incredibly fast answer.

Have a nice day.

**Comment by garemoko** [comment]
Making a new release now that fixes this.
